- name: setup jenkins server
  hosts: local
  become: yes
  tasks:
  - name: install package docker
    ansible.builtin.package:
      name: docker
      state: present
  - name: Start docker service
    ansible.builtin.service:
      name: docker
      state: started 
      enabled: yes
  - name: add ec2-user to docker group
    ansible.builtin.user:
      name: ec2-user
      groups: docker
      append: yes
  - name: install package java
    ansible.builtin.package:
      name: java-17-openjdk
      state: present
  - name: Download Jenkins Repo
    ansible.builtin.get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: Import Jenkins GPG key
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  - name: install package jenkins
    ansible.builtin.package:
      name: jenkins
      state: present
  - name: Start jenkins service
    ansible.builtin.service:
      name: jenkins
      state: started 
      enabled: yes