pipeline {
    agent  {
        node {
            label 'AGENT-1'
        }
    }
    environment { 
        appVersion = ''
        REGION = "us-west-2"
        ACC_ID = "441700732169"
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }
    // parameters {
    //     booleanParam(name: 'deploy', defaultValue: false, description: 'Toggle this value')
    // }
    // Build
    stages {
        stage('Read Version') {
            steps {
                script {
                    def packageJson = readJSON file: 'package.json'
                    appVersion = packageJson.version
                    echo "Package version: ${appVersion}"
                }
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                   sh """
                        npm install
                   """
                }
            }
        }
        stage('Unit Testing') {
            steps {
                script {
                   sh """
                        npm test
                   """
                }
            }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            echo 'Hello Failure'
        }
    }
}