pipeline {
    // These are pre-build sections
    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        COURSE = "Jenkins"
        appVersion = ""
        ACC_ID = "441700732169"
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
    }
    options {
        timeout(time: 10, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }
    // This is build section
    stages {
        stage('Read Version') {
            steps {
                script{
                    def packageJSON = readJSON file: 'catalogue/package.json'
                    appVersion = packageJSON.version
                    echo "app version: ${appVersion}"  
                }
            }
        }
        stage('Install Dependencies') {
            steps {
                script{
                    sh """
                        cd catalogue
                        npm install
                    """
                }
            }
        }
        stage('Unit Test') {
            steps {
                script{
                    sh """
                        cd catalogue
                        npm test || true
                    """
                }
            }
        }
        stage('Build Image') {
            steps {
                script{
                    withAWS(region:'us-west-2',credentials:'aws-creds') {
                        sh """
                            cd catalogue
                            aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${ACC_ID}.dkr.ecr.us-west-2.amazonaws.com
                            docker build -t ${ACC_ID}.dkr.ecr.us-west-2.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion} .
                            docker images
                            docker push ${ACC_ID}.dkr.ecr.us-west-2.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion}
                        """
                    }
                }
            }
        }
        stage('Trivy Scan'){
            steps {
                script{
                    sh """
                        trivy image \
                        --scanners vuln \
                        --severity HIGH,CRITICAL,MEDIUM \
                        --pkg-types os \
                        --exit-code 1 \
                        --format table \
                        ${ACC_ID}.dkr.ecr.us-west-2.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion}
                    """
                }
            }
        }
    }

}        

